#!/usr/bin/python

import sys

def get_brightness(bfile):
    """
    get the current brightness from bfile
    """
    with open(bfile, 'r') as f:
        br = int(f.readline())
    return br

def set_brightness(bfile, br):
    """
    set the brightness to br
    """
    with open(bfile, 'w') as f:
        f.write(str(int(br)))

def main():
    """
    Read the brightness file and perform the operation on it
    then write the new brightness to the file
    """

    # check number of args, print usage statement if incorrect
    if len(sys.argv) != 4 and len(sys.argv) != 3:
        print('usage: ' + sys.argv[0] + '  brightness_path ' \
                'operation [brightness]')
        print('possible operations: set, inc, dec, get')
        print('possible brightness: 0 - 100')
        sys.exit()

    # read arguments
    PATH = sys.argv[1]

    # check if / in path
    if PATH.strip()[-1] != "/":
        PATH += "/"

    # get system specific brightness values
    BFILE = PATH + "brightness"
    MBFILE = PATH + "max_brightness"
    with open(MBFILE, 'r') as f:
        MAX_BRIGHTNESS = int(f.readline())
    OP = sys.argv[2]
    if len(sys.argv) > 3:
        BRIGHTNESS = int(sys.argv[3]) # get brightness percentage
        BRIGHTNESS = MAX_BRIGHTNESS * (BRIGHTNESS / 100) # divide it by 100

    with open(BFILE, 'w+') as f:
        current_brightness = get_brightness(BFILE)  # read current brightness

        # set the brightness
        if OP == 'set':
            current_brightness = BRIGHTNESS
            if current_brightness < 0:
                current_brightness = 0
            elif current_brightness > MAX_BRIGHTNESS:
                current_brightness = MAX_BRIGHTNESS

        # increment the brightness
        elif OP == 'inc':
            current_brightness += BRIGHTNESS
            if current_brightness > MAX_BRIGHTNESS:
                current_brightness = MAX_BRIGHTNESS
    
        # decrement the brightness
        elif OP == 'dec':
            current_brightness -= BRIGHTNESS
            if current_brightness < 0:
                current_brightness = 0

        # get the brightness
        elif OP == 'get':
            print(int((current_brightness / MAX_BRIGHTNESS) * 100))
            sys.exit()

        # write to file
        set_brightness(BFILE, current_brightness)

    return

if __name__ == "__main__":
    main()

